name: x_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images\X_logo.png
    - images\Profile.jpg
    - images\TA.jpg
    - images\FKUPM.jpg
    - images\userImage.jpg
    - images\userImage1.jpg
    - images\userImage2.jpeg
    - images\userImage3.png
    - images\userImage4.jpg
    - images\beautiful_day.png
    - images\hello_world.png
    - images\exploring-new-horizons.jpg

