name: yaqoot_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: lib\fonts\Nunito-ExtraLight.ttf
          weight: 200
        - asset: lib\fonts\Nunito-Light.ttf
          weight: 300
        - asset: lib\fonts\Nunito-Medium.ttf
          weight: 500
        - asset: lib\fonts\Nunito-Regular.ttf
          weight: 400
        - asset: lib\fonts\Nunito-SemiBold.ttf
          weight: 600
  assets:
  - lib\assets\1-680x844.png
  - lib\assets\Apple_Watch.png
  - lib\assets\unlimited-pg.png
  - lib\assets\2-1-680x844.png
  - lib\assets\iPhone_15.png
  - lib\assets\OIP.jpg
  - lib\assets\icons\5g.png
  - lib\assets\icons\app.png
  - lib\assets\icons\clock.png
  - lib\assets\icons\giftbox.png
  - lib\assets\icons\help.png
  - lib\assets\icons\phone-call.png
  - lib\assets\icons\tachometer.png
  - lib\assets\icons\wifi-signal.png
  - lib\assets\sms-1.png
  - lib\assets\icons\close.png
  - lib\assets\icons\five.png
  - lib\assets\icons\one.png
  - lib\assets\icons\three.png
  - lib\assets\romingpackag_gcc_7.png
  - lib\assets\romingpackag_customize.png
  - lib\assets\internationalpackage_1.png
  - lib\assets\local-pkg.png
  - lib\assets\xiaomi.png
  - lib\assets\youtube.png
  - lib\assets\whatsapp.png
  - lib\assets\tiktok.png
  - lib\assets\telegram.png
  - lib\assets\snapchat.png
  - lib\assets\Yaqoot_logo.jpg
  - lib\assets\icons\settings.png
  - lib\assets\icons\sim-card.png
  - lib\assets\icons\twitter.png
  - lib\assets\icons\whatsapp (1).png
  - lib\assets\icons\headset.png
  - lib\assets\icons\instagram.png
  - lib\assets\icons\envelope.png
