name: discord_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter_svg: ^2.0.7
  overlapping_panels: ^0.0.3

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset:  assets/fonts/MyFlutterApp.ttf

  assets:
    - assets/icons/
    - assets/images/

